services:
  - type: web
    name: invoice-server
    env: docker
    rootDir: server
    plan: free
    dockerfilePath: server/Dockerfile
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_ENV
        value: PRODUCTION
      - key: FRONTEND_URL
        value: https://fiscal-own.vercel.app
      - key: BETTER_AUTH_SECRET
        generateValue: true
      - key: BETTER_AUTH_URL
        value: https://invoice-olua.onrender.com/api/auth
      - key: DATABASE_URL
        fromDatabase:
          name: invoice-db
          property: connectionString
    healthCheckPath: /
databases:
  - name: invoice-db
    plan: free

