services:
  - type: web
    name: invoice-server
    env: docker
    rootDir: server
    plan: free
    dockerfilePath: server/Dockerfile
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        sync: false
      - key: BETTER_AUTH_SECRET
        generateValue: true
      - key: BETTER_AUTH_URL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: invoice-db
          property: connectionString
    healthCheckPath: /
databases:
  - name: invoice-db
    plan: free

